require: rubocop-performance

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'app/channels/**/*'
    - 'app/concepts/**/*'
    - 'config/application.rb'
    - 'spec/support/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/controllers/resources/**'

Style/SignalException:
  Exclude:
    - 'app/concepts/**/*'

Lint/UnreachableCode:
  Exclude:
    - 'app/concepts/**/*'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
