require: rubocop-performance

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'config/**/*'
  IgnoredPatterns:
    - '\A#'
    - 'ctx\[\:error\]'
    - 'its\(\[:error\]\)'
    - 'include error\:'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'app/channels/**/*'
    - 'app/concepts/**/*'
    - 'config/application.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/controllers/resources/**'

Style/SignalException:
  Exclude:
    - 'app/concepts/**/*'

Lint/UnreachableCode:
  Exclude:
    - 'app/concepts/**/*'
