---
language: ruby
cache: bundler
services:
  - postgresql
  - redis
addons:
  postgresql: '9.6'
before_script:
  - psql -U postgres -f setup_postgres.sql
  - psql -d the_besieged_test -f /usr/share/postgresql/9.6/extension/pgcrypto--1.3.sql
  - RAILS_ENV=test bundle exec rails db:migrate
  - mv config/master.key.travis config/master.key
  - mv config/credentials.yml.enc.travis config/credentials.yml.enc
script:
  - bundle exec rubocop
  - bundle exec rspec
