default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: shared_world
  password: password

development:
  <<: *default
  database: shared_world_development

test:
  <<: *default
  database: shared_world_test

production:
  <<: *default
  database: shared_world_production
