default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: the_besieged
  password: password

development:
  <<: *default
  database: the_besieged_development

test:
  <<: *default
  database: the_besieged_test
